### ISSUE TITLE
Contraste insuficiente en las instrucciones del menú

### ISSUE THREAD

**Issue by BraisGlezArias** [Fernandolv123/Juego_Minimo#16]
Considero que las instrucciones del menú no están lo suficientemente nítidas con respecto al fondo oscuro del escenario en el menú principal.

![Fernando1](https://github.com/Fernandolv123/Juego_Minimo/assets/55207786/e939a8cd-a8ac-447f-a4a8-e2e3a64f9c00)

**Comment by Fernandolv123** [comment]
"Consideras"? si parece ciudad gótica por la noche.
Gracias por el feedback, realizaré los cambios tan pronto me sea posible
