### ISSUE TITLE
Botón de correr siendo shift da problemas

### ISSUE THREAD

**Issue by BraisGlezArias** [Fernandolv123/Juego_Minimo#20]
Al pulsar varias veces el botón de correr, aparece la molesta ventanita de "Activar Teclas Especiales". Esto se subsanaría cambiando dicho botón por otro menos odiado por los usuarios informáticos.

![Fernando5](https://github.com/Fernandolv123/Juego_Minimo/assets/55207786/d9db148f-7c17-49d2-908a-f73757801e4b)

**Comment by Fernandolv123** [comment]
Desgraciadamente ese no es un error que pueda controlar yo mismo, es un error propio de windows que debe configurarrse, lamento que hallas tenido malas experiencias con eso
