### ISSUE TITLE
Game build is not working

### ISSUE THREAD

**Issue by kevincerro-dvrv** [Fernandolv123/Juego_Minimo#21]
![image](https://github.com/Fernandolv123/Juego_Minimo/assets/148996189/3e5e41ee-4678-43c3-ad5e-eda955622fd1)

I downloaded zip and clicked the exe

**Comment by Fernandolv123** [comment]
Im sorry to hear that you had issues downloading the game, but you are the only one who had that problem so far, i'll investigate it, thank you for sending feedback
