### ISSUE TITLE
Typography have low contrast

### ISSUE THREAD

**Issue by kevincerro-dvrv** [Fernandolv123/Juego_Minimo#23]
Letters are not readable, some people with eye issues can have difficulties

![image](https://github.com/Fernandolv123/Juego_Minimo/assets/148996189/f4ecc2bf-ecbb-49ec-8e52-e350c302589c)

**Comment by Fernandolv123** [comment]
Yep, I received that same issue multiple times, i'm sorry your experience was worsen by that, thanks for feedback
