### ISSUE TITLE
Bug Reto Risa

### ISSUE THREAD

**Issue by diegoAG100** [Fernandolv123/Juego_Minimo#27]
En el reto de la risa, si lo completas te puedes ir para atras y el monstruo que aparece cada 30 segundos no te mata.

**Comment by Fernandolv123** [comment]
Se supone que no debería aparecer en este, ya que este pasillo se tarda más de lo normal en pasar, lamento la confusión y entiendo que haya sido un poco raro al no estar bien documentado, muchas gracias por tomarte tu tiempo probando mi juego!
